# Generated by Django 4.1.7 on 2023-03-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="incident_id",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
