# Generated by Django 4.1 on 2023-03-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident", "0003_alter_incident_incident_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="incident_id",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
